version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    ldflags:
      - -X github.com/noqqe/serra/pkg/serra.Version={{.Tag}}
    flags:
      - -v
    main: ./cmd/serra
archives:
  - id: serra
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: serra
    goarm: 6
    repository:
      owner: noqqe
      name: homebrew-tap
    download_strategy: CurlDownloadStrategy
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: "https://github.com/noqqe/serra"
    description: "serra - Personal Magic: The Gathering Collection Tracker "
    license: "MIT"
    test: |
      system "#{bin}/serra --version"
    install: |
      (share/"sounds").install "sounds/*mp3"
      bin.install "serra"
